-- Stoa Telegram bot — initial D1 schema.
-- Run: wrangler d1 execute stoa-bot-db --local --file=migrations/0001_init.sql

PRAGMA foreign_keys = ON;

-- ── users ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  telegram_user_id    INTEGER PRIMARY KEY,
  telegram_username   TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  -- Stored once the user accepts the custody disclosure on /start.
  disclosure_accepted_at TEXT
);

-- ── wallets ────────────────────────────────────────────────────────────────
-- One viem-generated EOA per Telegram user. Same address is used on
-- Arc Testnet (paying Stoa fees) and Base (funding Limitless sub-account).
CREATE TABLE IF NOT EXISTS wallets (
  telegram_user_id    INTEGER PRIMARY KEY REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  address             TEXT NOT NULL UNIQUE,
  -- AES-GCM(WALLET_ENCRYPTION_KEY, private_key_bytes). Base64-encoded:
  -- 12 bytes IV || ciphertext (32 bytes) || 16 bytes auth tag.
  pk_ciphertext_b64   TEXT NOT NULL,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ── limitless_sub_accounts ────────────────────────────────────────────────
-- Limitless server-wallet sub-accounts. Created on first /analyze or
-- on demand. Optional in v0 (mocked) but the schema is in place.
CREATE TABLE IF NOT EXISTS limitless_sub_accounts (
  telegram_user_id    INTEGER PRIMARY KEY REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  profile_id          INTEGER NOT NULL,                 -- Limitless internal id
  on_chain_address    TEXT NOT NULL,                    -- managed Privy wallet on Base
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ── prepared_orders ───────────────────────────────────────────────────────
-- Output of /analyze. /confirm <orderId> looks up the row and submits.
-- Mocked Limitless orderId is persisted post-/confirm for /positions display.
CREATE TABLE IF NOT EXISTS prepared_orders (
  order_id            TEXT PRIMARY KEY,                 -- UUIDv4 generated by bot
  telegram_user_id    INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  market_url          TEXT NOT NULL,
  market_slug         TEXT,
  market_question     TEXT,
  token_id            TEXT,                             -- Limitless YES/NO id
  side                TEXT,                             -- BUY | SELL
  price               REAL,
  size                REAL,
  recommended_size_usdc REAL,
  signal              TEXT,                             -- YES | NO | PASS
  confidence          REAL,
  trace_hash          TEXT,
  ipfs_cid            TEXT,
  pinned_tx           TEXT,                             -- Arc tx hash from TracePin
  analyze_settle_tx   TEXT,                             -- Arc tx hash from /analyze split
  confirm_settle_tx   TEXT,                             -- Arc tx hash from /confirm split
  limitless_order_id  TEXT,                             -- filled when /confirm submits
  status              TEXT NOT NULL DEFAULT 'prepared', -- prepared | confirmed | cancelled | failed
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  confirmed_at        TEXT
);
CREATE INDEX IF NOT EXISTS prepared_orders_user_idx ON prepared_orders(telegram_user_id);
CREATE INDEX IF NOT EXISTS prepared_orders_status_idx ON prepared_orders(status);

-- ── fee_charges ───────────────────────────────────────────────────────────
-- Audit log of every Stoa-routed payment. One row per /analyze, one per
-- /confirm. Lets us reconcile what was charged vs. what the operator received.
CREATE TABLE IF NOT EXISTS fee_charges (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  telegram_user_id    INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  command             TEXT NOT NULL,                    -- 'analyze' | 'confirm'
  related_order_id    TEXT REFERENCES prepared_orders(order_id) ON DELETE SET NULL,
  amount_usdc_micro   INTEGER NOT NULL,                 -- 100000 = $0.10
  tx_hash             TEXT,                             -- Arc tx hash from settle()
  status              TEXT NOT NULL DEFAULT 'pending',  -- pending | submitted | mined | failed
  error_msg           TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  mined_at            TEXT
);
CREATE INDEX IF NOT EXISTS fee_charges_user_idx ON fee_charges(telegram_user_id);
CREATE INDEX IF NOT EXISTS fee_charges_order_idx ON fee_charges(related_order_id);

-- ── trace_pins ─────────────────────────────────────────────────────────────
-- Mirror of TracePin events for /analyze runs. Joined with prepared_orders
-- via trace_hash for /preview displays.
CREATE TABLE IF NOT EXISTS trace_pins (
  trace_hash          TEXT PRIMARY KEY,
  telegram_user_id    INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  ipfs_cid            TEXT,
  arc_tx_hash         TEXT NOT NULL,
  market_url          TEXT NOT NULL,
  signal              TEXT,
  confidence          REAL,
  full_trace_json     TEXT NOT NULL,                    -- pretty FullTrace for /preview replay
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ── withdrawals ────────────────────────────────────────────────────────────
-- Audit log for /withdraw transfers.
CREATE TABLE IF NOT EXISTS withdrawals (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  telegram_user_id    INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  to_address          TEXT NOT NULL,
  amount_usdc_micro   INTEGER NOT NULL,
  chain               TEXT NOT NULL,                    -- 'base' | 'arc-testnet'
  tx_hash             TEXT,
  status              TEXT NOT NULL DEFAULT 'pending',
  error_msg           TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);
